export const ProjectsInfo = [
    {
        id: "0",
        name: "Skoll",
        logo: "./projects/project1/logo.png",
        desc: "Design and implementation of landing page, branding and mockups for a craft beer company. Conceptual project using Figma tools for design and HTML, CSS, JS for layout and responsive. Blender for mockups and 3D packaging.",
        image:"./projects/project1/featured_1.png",
        tag1:"HTML",
        tag2:"CSS",
        tag3:"JS",
        url:"https://juangeoo.github.io/skoll/",
        githubURL:"",
        pos:"left",

        slide1: "./projects/project1/slide1.png",
        slide3: "./projects/project1/slide3.png",
        slide4: "./projects/project1/slide4.png",
        slide5: "./projects/project1/slide5.png",
        slide6: "./projects/project1/slide6.png",
        slide7: "./projects/project1/slide7.png",
        slide8: "./projects/project1/slide8.png",
        slide9: "./projects/project1/slide9.png",
        slide10: "./projects/project1/slide10.png",
        slide11: "./projects/project1/slide11.png",
        slide12: "./projects/project1/slide12.png",
        slide13: "./projects/project1/slide13.png",
        slide14: "./projects/project1/slide14.png",
        nextproject: "./projects/project2/slide1.png",
    },
    {
        id: "1",
        name: "Nexus",
        logo: "./projects/project2/logo.png",
        desc: "Responsive landing page and branding for a cryptocurrency card called Nexus. Made with React JS, styled-components and Figma.",
        image:"./projects/project2/featured_2.png",
        tag1:"React JS",
        tag2:"Figma",
        tag3:"JS",
        url:"https://juangeoo.github.io/nexus/",
        githubURL:"",
        pos:"right",

        slide1: "./projects/project2/slide1.png",
        slide3: "./projects/project2/slide3.png",
        slide4: "./projects/project2/slide4.png",
        slide5: "./projects/project2/slide5.png",
        slide6: "./projects/project2/slide6.png",
        slide7: "./projects/project2/slide7.png",
        slide8: "./projects/project2/slide8.png",
        slide9: "./projects/project2/slide9.png",
        slide10: "./projects/project2/slide10.png",
        slide11: "./projects/project2/slide11.png",
        slide12: "./projects/project2/slide12.png",
        slide13: "./projects/project2/slide13.png",
        slide14: "./projects/project2/slide14.png",
        nextproject: "./projects/project3/slide1.png",
    },
    {
        id: "2",
        name: "Weather.app",
        logo: "./projects/project3/logo.png",
        desc: "Simple application with responsive design to know the current temperature in thousands of cities around the world with the use of OpenWeatherAPI, information and dynamic images that change depending on the city.",
        image:"./projects/project3/featured_3.png",
        tag1:"React JS",
        tag2:"API",
        tag3:"Styled Components",
        url:"https://juangeoo.github.io/weather-app/",
        githubURL:"",
        pos:"left",

        slide1: "./projects/project3/slide1.png",
        slide3: "./projects/project3/slide3.png",
        slide4: "./projects/project3/slide4.png",
        slide5: "./projects/project3/slide5.png",
        slide6: "./projects/project3/slide6.png",
        slide7: "./projects/project3/slide7.png",
        slide8: "./projects/project3/slide8.png",
        slide9: "./projects/project3/slide9.png",
        slide10: "./projects/project3/slide10.png",
        slide11: "./projects/project3/slide11.png",
        slide12: "./projects/project3/slide12.png",
        slide13: "./projects/project3/slide13.png",
        slide14: "./projects/project3/slide14.png",
        nextproject: "./projects/project4/slide1.png",
    },
    {
        id: "3",
        name: "WatchBox",
        logo: "./projects/project4/logo.png",
        desc: "Application to search for any movie with dynamic information using the OpenMovieDatabase API. Made with React JS and designed in Figma.",
        image:"./projects/project4/featured_4.png",
        tag1:"React JS",
        tag2:"API",
        tag3:"Styled Components",
        url:"https://juangeoo.github.io/watchbox/",
        githubURL:"",
        pos:"right",

        slide1: "./projects/project4/slide1.png",
        slide3: "./projects/project4/slide3.png",
        slide4: "./projects/project4/slide4.png",
        slide5: "./projects/project4/slide5.png",
        slide6: "./projects/project4/slide6.png",
        slide7: "./projects/project4/slide7.png",
        slide8: "./projects/project4/slide8.png",
        slide9: "./projects/project4/slide9.png",
        slide10: "./projects/project4/slide10.png",
        slide11: "./projects/project4/slide11.png",
        slide12: "./projects/project4/slide12.png",
        slide13: "./projects/project4/slide13.png",
        slide14: "./projects/project4/slide14.png",
        nextproject: "./projects/project1/slide1.png",
    },
    {
        id: "7",
        name: "Explorway",
        logo: "./projects/project8/logo.png",
        desc: "Made the front end for a conceptual travel and tourism landing page, original design by OuterStudio",
        image:"./projects/project8/featured_8.png",
        tag1:"React JS",
        tag2:"Framer Motion",
        tag3:"HTML/SCSS",
        url:"https://juangeoo.github.io/explorway/",
        githubURL:"",
        pos:"left",
    },

    
]
